# Generated by Django 4.2.10 on 2025-09-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='作者名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app01.author', verbose_name='作者详情')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, verbose_name='电话')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='出版社名')),
                ('address', models.CharField(max_length=50, verbose_name='出版社地址')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, verbose_name='用户名')),
                ('password', models.CharField(max_length=25, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('publish_date', models.DateField(auto_now_add=True, verbose_name='出版日期')),
                ('authors', models.ManyToManyField(related_name='books', to='app01.author', verbose_name='作者')),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app01.publish', verbose_name='出版社')),
            ],
        ),
    ]
