# Generated by Django 4.2.10 on 2025-09-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_book_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='details',
            new_name='detail',
        ),
    ]
