# Generated by Django 4.2.10 on 2025-09-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_rename_details_author_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app01.authordetail', verbose_name='作者详情'),
        ),
    ]
